# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ddd5d08e716b23143ae41602e0747c125120646211053800529286266a2fd82fe61b294acc047fb76d86b32094e9e82c9e45b400a9c80d02bab4f20d22b4ae3

test:
  secret_key_base: daa4c244db4eb8cca80af6c314bb3c593d2ae3a3d9d6c6c1c234286e1e5ec143d9b211409b25a6b60a0d744f29d460e84953561c7f4d461b4251994ed1356f72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
